In [1]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')
import sqlite3
import traceback
import csv
from sqlalchemy import create_engine, text

In [2]:
csvOutputFile = './output_directory_path/percent_child_poverty_data.csv'
e = create_engine('sqlite:///child_poverty.db')
if not os.path.isfile('child_poverty.db'):
    file_path_2023 = 'Recources/2023.xlsx'
    df_2023 = pd.read_excel(file_path_2023)

    file_path_2022 = 'Recources/2022.xlsx'
    df_2022 = pd.read_excel(file_path_2022)

    file_path_2021 = 'Recources/2021.xlsx'
    df_2021 = pd.read_excel(file_path_2021)

    file_path_2020 = 'Recources/2020.xlsx'
    df_2020 = pd.read_excel(file_path_2020)

    file_path_2019 = 'Recources/2019.xlsx'
    df_2019 = pd.read_excel(file_path_2019)

    file_path_2018 = 'Recources/2018.xlsx'
    df_2018 = pd.read_excel(file_path_2018)

    file_path_2017 = 'Recources/2017.xlsx'
    df_2017 = pd.read_excel(file_path_2017)

    file_path_2016 = 'Recources/2016.xlsx'
    df_2016 = pd.read_excel(file_path_2016)

    file_path_2015 = 'Recources/2015.xlsx'
    df_2015 = pd.read_excel(file_path_2015)

    file_path_2014 = 'Recources/2014.xlsx'
    df_2014 = pd.read_excel(file_path_2014)

    file_path_2013 = 'Recources/2013.xlsx'
    df_2013 = pd.read_excel(file_path_2013)

  
    df_2013.to_sql('df_2013', e, if_exists='append')
    df_2014.to_sql('df_2014', e, if_exists='append')
    df_2015.to_sql('df_2015', e, if_exists='append')
    df_2016.to_sql('df_2016', e, if_exists='append')
    df_2017.to_sql('df_2017', e, if_exists='append')
    df_2018.to_sql('df_2018', e, if_exists='append')
    df_2019.to_sql('df_2019', e, if_exists='append')
    df_2020.to_sql('df_2020', e, if_exists='append')
    df_2021.to_sql('df_2021', e, if_exists='append')
    df_2022.to_sql('df_2022', e, if_exists='append')
    df_2023.to_sql('df_2023', e, if_exists='append')

else:
    df_2013 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2013')))
    df_2014 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2014')))
    df_2015 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2015')))
    df_2016 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2016')))
    df_2017 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2017')))
    df_2018 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2018')))
    df_2019 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2019')))
    df_2020 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2020')))
    df_2021 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2021')))
    df_2022 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2022')))
    df_2023 = pd.DataFrame(e.connect().execute(text('SELECT * FROM df_2023')))

In [3]:
desired_columns_2023 = ['FIPS', 'State', 'County', '% Children in Poverty']
df_2023 = df_2023[desired_columns_2023]

desired_columns_2022 = ['FIPS', '% Children in Poverty']
df_2022 = df_2022[desired_columns_2022]

desired_columns_2021 = ['FIPS', '% Children in Poverty']
df_2021 = df_2021[desired_columns_2021]

desired_columns_2020 = ['FIPS', '% Children in Poverty']
df_2020 = df_2020[desired_columns_2020]

desired_columns_2019 = ['FIPS', '% Children in Poverty']
df_2019 = df_2019[desired_columns_2019]

desired_columns_2018 = ['FIPS', '% Children in Poverty']
df_2018 = df_2018[desired_columns_2018]

desired_columns_2017 = ['FIPS', '% Children in Poverty']
df_2017 = df_2017[desired_columns_2017]

desired_columns_2016 = ['FIPS', '% Children in Poverty']
df_2016 = df_2016[desired_columns_2016]

desired_columns_2015 = ['FIPS', '% Children in Poverty']
df_2015 = df_2015[desired_columns_2015]

desired_columns_2014 = ['FIPS', '% Children in Poverty']
df_2014 = df_2014[desired_columns_2014]

desired_columns_2013 = ['FIPS', '% Children in Poverty']
df_2013 = df_2013[desired_columns_2013]

In [4]:
column_name= '% Children in Poverty'
new_column_name_2023 = f'{column_name}_2023'  # Modify the column name accordingly
df_2023.rename(columns={column_name: new_column_name_2023}, inplace=True)

new_column_name_2022 = f'{column_name}_2022'  # Modify the column name accordingly
df_2022.rename(columns={column_name: new_column_name_2022}, inplace=True)

new_column_name_2021 = f'{column_name}_2021' # Modify the column name accordingly
df_2021.rename(columns={column_name: new_column_name_2021}, inplace=True)

new_column_name_2020 = f'{column_name}_2020'  # Modify the column name accordingly
df_2020.rename(columns={column_name: new_column_name_2020}, inplace=True)

new_column_name_2019 = f'{column_name}_2019'  # Modify the column name accordingly
df_2019.rename(columns={column_name: new_column_name_2019}, inplace=True)

new_column_name_2018 = f'{column_name}_2018'  # Modify the column name accordingly
df_2018.rename(columns={column_name: new_column_name_2018}, inplace=True)

new_column_name_2017 = f'{column_name}_2017'  # Modify the column name accordingly
df_2017.rename(columns={column_name: new_column_name_2017}, inplace=True)

new_column_name_2016 = f'{column_name}_2016'  # Modify the column name accordingly
df_2016.rename(columns={column_name: new_column_name_2016}, inplace=True)

new_column_name_2015 = f'{column_name}_2015'  # Modify the column name accordingly
df_2015.rename(columns={column_name: new_column_name_2015}, inplace=True)

new_column_name_2014 = f'{column_name}_2014' # Modify the column name accordingly
df_2014.rename(columns={column_name: new_column_name_2014}, inplace=True)

new_column_name_2013 = f'{column_name}_2013'  # Modify the column name accordingly
df_2013.rename(columns={column_name: new_column_name_2013}, inplace=True)

In [5]:
df_merged = pd.merge(df_2022, df_2023, on='FIPS', how='left')
df_merged = pd.merge(df_merged, df_2021, on='FIPS', how='left')
df_merged = pd.merge(df_merged, df_2020, on='FIPS', how='left')
df_merged = pd.merge(df_merged, df_2019, on='FIPS', how='left')
df_merged = pd.merge(df_merged, df_2018, on='FIPS', how='left')
df_merged = pd.merge(df_merged, df_2017, on='FIPS', how='left')
df_merged = pd.merge(df_merged, df_2016, on='FIPS', how='left')
df_merged = pd.merge(df_merged, df_2015, on='FIPS', how='left')
df_merged = pd.merge(df_merged, df_2014, on='FIPS', how='left')
df_merged = pd.merge(df_merged, df_2013, on='FIPS', how='left')

df_merged

,FIPS,% Children in Poverty_2022,State,County,% Children in Poverty_2023,% Children in Poverty_2021,% Children in Poverty_2020,% Children in Poverty_2019,% Children in Poverty_2018,% Children in Poverty_2017,% Children in Poverty_2016,% Children in Poverty_2015,% Children in Poverty_2014,% Children in Poverty_2013
0,1000,20.9,Alabama,NaN,22.7,21.9,23.9,NaN,NaN,NaN,NaN,NaN,NaN,27.6
1,1001,14.9,Alabama,Autauga,16.1,15.9,19.3,19.3,19.3,18.8,18.1,19.6,18.5,21.0
2,1003,12.4,Alabama,Baldwin,16.4,13.5,13.9,14.7,17.6,19.6,19.8,20.8,20.5,20.5
3,1005,37.5,Alabama,Barbour,35.1,41.0,43.9,50.3,39.6,45.2,38.1,42.4,47.0,39.8
4,1007,21.9,Alabama,Bibb,29.0,25.9,27.8,27.3,27.5,29.3,26.8,35.6,27.2,30.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,8.4,Wyoming,Sweetwater,9.7,10.1,10.0,13.4,9.2,10.2,11.9,11.3,11.5,14.9
3189,56039,4.3,Wyoming,Teton,5.5,5.7,6.7,6.9,6.7,7.6,9.5,10.5,14.2,14.9
3190,56041,9.7,Wyoming,Uinta,11.2,9.6,12.1,11.8,11.3,11.9,12.6,13.5,16.0,13.7
3191,56043,10.7,Wyoming,Washakie,12.5,13.9,16.1,14.0,15.2,15.7,16.2,14.5,18.3,15.4
3192,56045,12.6,Wyoming,Weston,12.3,13.8,16.1,14.0,14.1,13.1,18.4,12.2,14.1,15.6

In [6]:
output_directory = 'output_directory_path'
if not os.path.exists(output_directory):
    os.makedirs(output_directory)
    
output_filename = 'percent_children_poverty_data.xlsx'
output_file = os.path.join(output_directory, output_filename)

df_merged.dropna(subset=['FIPS'], inplace=True)
df_merged['FIPS'] = df_merged['FIPS'].astype(str).str.zfill(5)
columns = df_merged.columns.tolist()
columns.insert(4, columns.pop(1))
df_merged = df_merged[columns]
start_pos = 3
end_pos = 13
columns = df_merged.columns.tolist()
subset_columns = columns[start_pos:end_pos+1]
subset_columns.reverse()
columns[start_pos:end_pos+1] = subset_columns
df_merged = df_merged[columns]
df_merged.iloc[:, 3:14] = df_merged.iloc[:, 3:14].round(1)
df_merged.to_excel(output_file, index=False)
df_merged.fillna(0, inplace=True)
df_merged = df_merged[df_merged.iloc[:, 2] != 0]
df_merged = df_merged.replace(' ', '_', regex=True)
df_merged = df_merged.replace('% Children in Poverty', '%_Children_in_Poverty', regex=True)

# df_merged.to_sql('df_merged', e, if_exists='append')

df_merged

,FIPS,State,County,% Children in Poverty_2013,% Children in Poverty_2014,% Children in Poverty_2015,% Children in Poverty_2016,% Children in Poverty_2017,% Children in Poverty_2018,% Children in Poverty_2019,% Children in Poverty_2020,% Children in Poverty_2021,% Children in Poverty_2022,% Children in Poverty_2023
1,01001,Alabama,Autauga,21.0,18.5,19.6,18.1,18.8,19.3,19.3,19.3,15.9,14.9,16.1
2,01003,Alabama,Baldwin,20.5,20.5,20.8,19.8,19.6,17.6,14.7,13.9,13.5,12.4,16.4
3,01005,Alabama,Barbour,39.8,47.0,42.4,38.1,45.2,39.6,50.3,43.9,41.0,37.5,35.1
4,01007,Alabama,Bibb,30.5,27.2,35.6,26.8,29.3,27.5,27.3,27.8,25.9,21.9,29.0
5,01009,Alabama,Blount,22.2,23.1,26.6,24.1,22.2,19.4,18.5,18.0,21.0,18.9,16.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Wyoming,Sweetwater,14.9,11.5,11.3,11.9,10.2,9.2,13.4,10.0,10.1,8.4,9.7
3189,56039,Wyoming,Teton,14.9,14.2,10.5,9.5,7.6,6.7,6.9,6.7,5.7,4.3,5.5
3190,56041,Wyoming,Uinta,13.7,16.0,13.5,12.6,11.9,11.3,11.8,12.1,9.6,9.7,11.2
3191,56043,Wyoming,Washakie,15.4,18.3,14.5,16.2,15.7,15.2,14.0,16.1,13.9,10.7,12.5
3192,56045,Wyoming,Weston,15.6,14.1,12.2,18.4,13.1,14.1,14.0,16.1,13.8,12.6,12.3

In [7]:
X = df_merged.iloc[:, 3:12]  
y = df_merged['% Children in Poverty_2023']

In [8]:
X_encoded = pd.get_dummies(X, drop_first=True)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

In [9]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred = model.predict(X_test)

In [11]:
r_squared = r2_score(y_test, y_pred)
print('R-squared:', r_squared)

R-squared: 0.9296094430298143

In [12]:
output_directory = 'output_directory_path'
output_filename = 'predictions_%_Children_in_Poverty_2023.xlsx'
output_file = os.path.join(output_directory, output_filename)

In [13]:
predictions_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
predictions_df.to_excel(output_file, index=False)
print(f"Predictions exported to: {output_file}")

Predictions exported to: output_directory_path\predictions_%_Children_in_Poverty_2023.xlsx

In [14]:
# Predict values for 2024
copied_df_2024 = df_merged.copy()

In [15]:
X_2024 = copied_df_2024.iloc[:, 3:13]

In [16]:
X_2024_encoded = pd.get_dummies(X_2024, drop_first=True)
X_2024_encoded = X_2024_encoded.reindex(columns=X_train.columns, fill_value=0)

In [17]:
y_pred_2024 = model.predict(X_2024_encoded)

In [18]:
copied_df_2024['% Children in Poverty_2024'] = y_pred_2024

In [19]:
output_filename_2024 = 'predictions_%_Children_in_Poverty_2024.xlsx'
output_file_2024 = os.path.join(output_directory, output_filename_2024)
copied_df_2024.to_excel(output_file_2024, index=False)
print(f"Predictions for 2024 exported to: {output_file_2024}")

Predictions for 2024 exported to: output_directory_path\predictions_%_Children_in_Poverty_2024.xlsx

In [20]:
output_directory = 'output_directory_path'
output_filename = 'copied_df_%_Children_in_Poverty_2024.xlsx'
output_file = os.path.join(output_directory, output_filename)

copied_df_2024.to_excel(output_file, index=False)
print(f"DataFrame exported to: {output_file}")

DataFrame exported to: output_directory_path\copied_df_%_Children_in_Poverty_2024.xlsx

In [21]:
copied_df_2024

,FIPS,State,County,% Children in Poverty_2013,% Children in Poverty_2014,% Children in Poverty_2015,% Children in Poverty_2016,% Children in Poverty_2017,% Children in Poverty_2018,% Children in Poverty_2019,% Children in Poverty_2020,% Children in Poverty_2021,% Children in Poverty_2022,% Children in Poverty_2023,% Children in Poverty_2024
1,01001,Alabama,Autauga,21.0,18.5,19.6,18.1,18.8,19.3,19.3,19.3,15.9,14.9,16.1,17.397593
2,01003,Alabama,Baldwin,20.5,20.5,20.8,19.8,19.6,17.6,14.7,13.9,13.5,12.4,16.4,14.174577
3,01005,Alabama,Barbour,39.8,47.0,42.4,38.1,45.2,39.6,50.3,43.9,41.0,37.5,35.1,41.004279
4,01007,Alabama,Bibb,30.5,27.2,35.6,26.8,29.3,27.5,27.3,27.8,25.9,21.9,29.0,25.417112
5,01009,Alabama,Blount,22.2,23.1,26.6,24.1,22.2,19.4,18.5,18.0,21.0,18.9,16.7,18.249726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Wyoming,Sweetwater,14.9,11.5,11.3,11.9,10.2,9.2,13.4,10.0,10.1,8.4,9.7,10.214112
3189,56039,Wyoming,Teton,14.9,14.2,10.5,9.5,7.6,6.7,6.9,6.7,5.7,4.3,5.5,6.145967
3190,56041,Wyoming,Uinta,13.7,16.0,13.5,12.6,11.9,11.3,11.8,12.1,9.6,9.7,11.2,10.703357
3191,56043,Wyoming,Washakie,15.4,18.3,14.5,16.2,15.7,15.2,14.0,16.1,13.9,10.7,12.5,14.156794
3192,56045,Wyoming,Weston,15.6,14.1,12.2,18.4,13.1,14.1,14.0,16.1,13.8,12.6,12.3,13.866780

In [22]:
# Predict values for 2025
input_file = 'output_directory_path/copied_df_%_Children_in_Poverty_2024.xlsx'
df_merged = pd.read_excel(input_file)

In [23]:
X = df_merged.iloc[:, 3:13].values  # Features from 2013 to 2023
y = df_merged.iloc[:, 14].values    # Target variable for 2024 (Column 15)

In [24]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [25]:
model = LinearRegression()
model.fit(X_scaled, y)

LinearRegression()

In [26]:
features_2025 = df_merged.iloc[:, 4:14].values  # Features from 2014 to 2024
features_2025_scaled = scaler.transform(features_2025)

In [27]:
predictions_2025 = model.predict(features_2025_scaled)

In [28]:
df_merged['% Children in Poverty_2025'] = predictions_2025

In [29]:
r_squared = r2_score(y, model.predict(X_scaled))
print("R-squared:", r_squared)

R-squared: 1.0

In [30]:
df_merged

,FIPS,State,County,% Children in Poverty_2013,% Children in Poverty_2014,% Children in Poverty_2015,% Children in Poverty_2016,% Children in Poverty_2017,% Children in Poverty_2018,% Children in Poverty_2019,% Children in Poverty_2020,% Children in Poverty_2021,% Children in Poverty_2022,% Children in Poverty_2023,% Children in Poverty_2024,% Children in Poverty_2025
0,1001,Alabama,Autauga,21.0,18.5,19.6,18.1,18.8,19.3,19.3,19.3,15.9,14.9,16.1,17.397593,16.478411
1,1003,Alabama,Baldwin,20.5,20.5,20.8,19.8,19.6,17.6,14.7,13.9,13.5,12.4,16.4,14.174577,12.922886
2,1005,Alabama,Barbour,39.8,47.0,42.4,38.1,45.2,39.6,50.3,43.9,41.0,37.5,35.1,41.004279,39.814355
3,1007,Alabama,Bibb,30.5,27.2,35.6,26.8,29.3,27.5,27.3,27.8,25.9,21.9,29.0,25.417112,24.081480
4,1009,Alabama,Blount,22.2,23.1,26.6,24.1,22.2,19.4,18.5,18.0,21.0,18.9,16.7,18.249726,17.902803
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56037,Wyoming,Sweetwater,14.9,11.5,11.3,11.9,10.2,9.2,13.4,10.0,10.1,8.4,9.7,10.214112,9.938755
3138,56039,Wyoming,Teton,14.9,14.2,10.5,9.5,7.6,6.7,6.9,6.7,5.7,4.3,5.5,6.145967,5.581188
3139,56041,Wyoming,Uinta,13.7,16.0,13.5,12.6,11.9,11.3,11.8,12.1,9.6,9.7,11.2,10.703357,10.235203
3140,56043,Wyoming,Washakie,15.4,18.3,14.5,16.2,15.7,15.2,14.0,16.1,13.9,10.7,12.5,14.156794,12.993296
3141,56045,Wyoming,Weston,15.6,14.1,12.2,18.4,13.1,14.1,14.0,16.1,13.8,12.6,12.3,13.866780,13.497110

In [31]:
output_file = 'output_directory_path/copied_df_%_Children_in_Poverty_2025.xlsx'
df_merged.to_excel(output_file, index=False)
print(f"DataFrame successfully exported to {output_file}")

DataFrame successfully exported to output_directory_path/copied_df_%_Children_in_Poverty_2025.xlsx

In [32]:
# Predict values for 2026
input_file = 'output_directory_path/copied_df_%_Children_in_Poverty_2025.xlsx'
df_merged = pd.read_excel(input_file)

In [33]:
X = df_merged.iloc[:, 3:14].values  # Features from 2013 to 2024
y = df_merged.iloc[:, 15].values    # Target variable for 2025 (Column 15)

In [34]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [35]:
model = LinearRegression()
model.fit(X_scaled, y)

LinearRegression()

In [36]:
features_2026 = df_merged.iloc[:, 4:15].values  # Features from 2014 to 2025
features_2026_scaled = scaler.transform(features_2026)

In [37]:
predictions_2026 = model.predict(features_2026_scaled)

In [38]:
df_merged['% Children in Poverty_2026'] = predictions_2026

In [39]:
r_squared = r2_score(y, model.predict(X_scaled))
print("R-squared:", r_squared)

R-squared: 1.0

In [40]:
df_merged

,FIPS,State,County,% Children in Poverty_2013,% Children in Poverty_2014,% Children in Poverty_2015,% Children in Poverty_2016,% Children in Poverty_2017,% Children in Poverty_2018,% Children in Poverty_2019,% Children in Poverty_2020,% Children in Poverty_2021,% Children in Poverty_2022,% Children in Poverty_2023,% Children in Poverty_2024,% Children in Poverty_2025,% Children in Poverty_2026
0,1001,Alabama,Autauga,21.0,18.5,19.6,18.1,18.8,19.3,19.3,19.3,15.9,14.9,16.1,17.397593,16.478411,15.738135
1,1003,Alabama,Baldwin,20.5,20.5,20.8,19.8,19.6,17.6,14.7,13.9,13.5,12.4,16.4,14.174577,12.922886,13.202425
2,1005,Alabama,Barbour,39.8,47.0,42.4,38.1,45.2,39.6,50.3,43.9,41.0,37.5,35.1,41.004279,39.814355,37.124261
3,1007,Alabama,Bibb,30.5,27.2,35.6,26.8,29.3,27.5,27.3,27.8,25.9,21.9,29.0,25.417112,24.081480,24.319750
4,1009,Alabama,Blount,22.2,23.1,26.6,24.1,22.2,19.4,18.5,18.0,21.0,18.9,16.7,18.249726,17.902803,17.308254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56037,Wyoming,Sweetwater,14.9,11.5,11.3,11.9,10.2,9.2,13.4,10.0,10.1,8.4,9.7,10.214112,9.938755,9.432557
3138,56039,Wyoming,Teton,14.9,14.2,10.5,9.5,7.6,6.7,6.9,6.7,5.7,4.3,5.5,6.145967,5.581188,5.443327
3139,56041,Wyoming,Uinta,13.7,16.0,13.5,12.6,11.9,11.3,11.8,12.1,9.6,9.7,11.2,10.703357,10.235203,10.245111
3140,56043,Wyoming,Washakie,15.4,18.3,14.5,16.2,15.7,15.2,14.0,16.1,13.9,10.7,12.5,14.156794,12.993296,12.643467
3141,56045,Wyoming,Weston,15.6,14.1,12.2,18.4,13.1,14.1,14.0,16.1,13.8,12.6,12.3,13.866780,13.497110,13.083712

In [41]:
output_file = 'output_directory_path/copied_df_%_Children_in_Poverty_2026.xlsx'
df_merged.to_excel(output_file, index=False)
print(f"DataFrame successfully exported to {output_file}")

DataFrame successfully exported to output_directory_path/copied_df_%_Children_in_Poverty_2026.xlsx

In [42]:
# Predict values for 2027
input_file = 'output_directory_path/copied_df_%_Children_in_Poverty_2026.xlsx'
df_merged = pd.read_excel(input_file)

In [43]:
X = df_merged.iloc[:, 3:15].values  # Features from 2013 to 2024
y = df_merged.iloc[:, 16].values    # Target variable for 2025 (Column 15)

In [44]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [45]:
model = LinearRegression()
model.fit(X_scaled, y)

LinearRegression()

In [46]:
features_2027 = df_merged.iloc[:, 4:16].values  # Features from 2014 to 2026
features_2027_scaled = scaler.transform(features_2027)

In [47]:
predictions_2027 = model.predict(features_2027_scaled)

In [48]:
df_merged['% Children in Poverty_2027'] = predictions_2027

In [49]:
r_squared = r2_score(y, model.predict(X_scaled))
print("R-squared:", r_squared)

R-squared: 1.0

In [50]:
df_merged

,FIPS,State,County,% Children in Poverty_2013,% Children in Poverty_2014,% Children in Poverty_2015,% Children in Poverty_2016,% Children in Poverty_2017,% Children in Poverty_2018,% Children in Poverty_2019,% Children in Poverty_2020,% Children in Poverty_2021,% Children in Poverty_2022,% Children in Poverty_2023,% Children in Poverty_2024,% Children in Poverty_2025,% Children in Poverty_2026,% Children in Poverty_2027
0,1001,Alabama,Autauga,21.0,18.5,19.6,18.1,18.8,19.3,19.3,19.3,15.9,14.9,16.1,17.397593,16.478411,15.738135,15.448752
1,1003,Alabama,Baldwin,20.5,20.5,20.8,19.8,19.6,17.6,14.7,13.9,13.5,12.4,16.4,14.174577,12.922886,13.202425,13.246288
2,1005,Alabama,Barbour,39.8,47.0,42.4,38.1,45.2,39.6,50.3,43.9,41.0,37.5,35.1,41.004279,39.814355,37.124261,36.471902
3,1007,Alabama,Bibb,30.5,27.2,35.6,26.8,29.3,27.5,27.3,27.8,25.9,21.9,29.0,25.417112,24.081480,24.319750,24.126782
4,1009,Alabama,Blount,22.2,23.1,26.6,24.1,22.2,19.4,18.5,18.0,21.0,18.9,16.7,18.249726,17.902803,17.308254,17.411854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56037,Wyoming,Sweetwater,14.9,11.5,11.3,11.9,10.2,9.2,13.4,10.0,10.1,8.4,9.7,10.214112,9.938755,9.432557,9.364319
3138,56039,Wyoming,Teton,14.9,14.2,10.5,9.5,7.6,6.7,6.9,6.7,5.7,4.3,5.5,6.145967,5.581188,5.443327,5.423395
3139,56041,Wyoming,Uinta,13.7,16.0,13.5,12.6,11.9,11.3,11.8,12.1,9.6,9.7,11.2,10.703357,10.235203,10.245111,10.060568
3140,56043,Wyoming,Washakie,15.4,18.3,14.5,16.2,15.7,15.2,14.0,16.1,13.9,10.7,12.5,14.156794,12.993296,12.643467,12.348812
3141,56045,Wyoming,Weston,15.6,14.1,12.2,18.4,13.1,14.1,14.0,16.1,13.8,12.6,12.3,13.866780,13.497110,13.083712,12.621590

In [51]:
df_merged.iloc[:, 14:18] = df_merged.iloc[:, 14:18].round(1)

In [52]:
output_file = 'output_directory_path/copied_df_%_Children_in_Poverty_2027.xlsx'
df_merged.to_excel(output_file, index=False)
print(f"DataFrame successfully exported to {output_file}")

DataFrame successfully exported to output_directory_path/copied_df_%_Children_in_Poverty_2027.xlsx

In [53]:
df_merged

,FIPS,State,County,% Children in Poverty_2013,% Children in Poverty_2014,% Children in Poverty_2015,% Children in Poverty_2016,% Children in Poverty_2017,% Children in Poverty_2018,% Children in Poverty_2019,% Children in Poverty_2020,% Children in Poverty_2021,% Children in Poverty_2022,% Children in Poverty_2023,% Children in Poverty_2024,% Children in Poverty_2025,% Children in Poverty_2026,% Children in Poverty_2027
0,1001,Alabama,Autauga,21.0,18.5,19.6,18.1,18.8,19.3,19.3,19.3,15.9,14.9,16.1,17.4,16.5,15.7,15.4
1,1003,Alabama,Baldwin,20.5,20.5,20.8,19.8,19.6,17.6,14.7,13.9,13.5,12.4,16.4,14.2,12.9,13.2,13.2
2,1005,Alabama,Barbour,39.8,47.0,42.4,38.1,45.2,39.6,50.3,43.9,41.0,37.5,35.1,41.0,39.8,37.1,36.5
3,1007,Alabama,Bibb,30.5,27.2,35.6,26.8,29.3,27.5,27.3,27.8,25.9,21.9,29.0,25.4,24.1,24.3,24.1
4,1009,Alabama,Blount,22.2,23.1,26.6,24.1,22.2,19.4,18.5,18.0,21.0,18.9,16.7,18.2,17.9,17.3,17.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56037,Wyoming,Sweetwater,14.9,11.5,11.3,11.9,10.2,9.2,13.4,10.0,10.1,8.4,9.7,10.2,9.9,9.4,9.4
3138,56039,Wyoming,Teton,14.9,14.2,10.5,9.5,7.6,6.7,6.9,6.7,5.7,4.3,5.5,6.1,5.6,5.4,5.4
3139,56041,Wyoming,Uinta,13.7,16.0,13.5,12.6,11.9,11.3,11.8,12.1,9.6,9.7,11.2,10.7,10.2,10.2,10.1
3140,56043,Wyoming,Washakie,15.4,18.3,14.5,16.2,15.7,15.2,14.0,16.1,13.9,10.7,12.5,14.2,13.0,12.6,12.3
3141,56045,Wyoming,Weston,15.6,14.1,12.2,18.4,13.1,14.1,14.0,16.1,13.8,12.6,12.3,13.9,13.5,13.1,12.6