In [27]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [28]:
input_file = 'output_directory_path/copied_df_2024.xlsx'
df_merged = pd.read_excel(input_file)

In [29]:
df_merged

,FIPS,State,County,2013_% Adults with Diabetes,2014_% Adults with Diabetes,2015_% Adults with Diabetes,2016_% Adults with Diabetes,2017_% Adults with Diabetes,2018_% Adults with Diabetes,2019_% Adults with Diabetes,2020_% Adults with Diabetes,2021_% Adults with Diabetes,2022_% Adults with Diabetes,2023_% Adults with Diabetes,2024_% Adults with Diabetes
0,1000,Alabama,0,12.7,0.0,0.0,0.0,0.0,0.0,0.0,14.2,14.5,12.2,13.0,11.1
1,1001,Alabama,Autauga,12.3,11.8,12.1,10.9,13.0,12.4,14.2,11.1,12.7,11.2,10.6,10.0
2,1003,Alabama,Baldwin,11.4,11.8,11.5,10.9,10.4,11.1,11.3,10.7,10.3,9.4,9.7,10.7
3,1005,Alabama,Barbour,14.0,14.2,14.8,15.3,18.4,18.2,18.0,17.6,17.5,16.5,15.6,12.8
4,1007,Alabama,Bibb,11.8,11.1,12.7,12.5,14.8,14.6,14.9,14.5,13.6,12.7,12.2,11.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Wyoming,Sweetwater,6.8,7.1,7.6,7.6,8.1,7.9,8.4,8.8,8.3,8.3,7.9,7.6
3189,56039,Wyoming,Teton,4.0,3.9,4.3,6.8,4.8,4.5,4.2,2.2,2.4,6.6,6.3,6.9
3190,56041,Wyoming,Uinta,7.0,7.4,8.2,8.3,9.0,10.0,9.3,11.3,10.3,8.3,7.8,8.9
3191,56043,Wyoming,Washakie,8.8,8.5,9.7,10.5,12.0,11.5,10.9,11.7,10.7,8.9,8.0,9.8
3192,56045,Wyoming,Weston,7.4,8.3,8.5,9.1,10.0,10.2,9.4,9.0,11.1,8.3,7.8,8.7

In [51]:
X = df_merged.iloc[:, 3:14].values  # Features from 2013 to 2024
y = df_merged.iloc[:, 14].values    # Target variable for 2024

In [52]:
# Step 2: Train a Linear Regression Model
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [53]:
# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

LinearRegression()

In [54]:
# Create and train the Linear Regression model
model = LinearRegression()
model.fit(X_train_scaled, y_train)

In [55]:
# Step 3: Make Predictions for 2025
# Features for 2025 will be the last row of the original data (columns 4 to 14)
features_2025 = df_merged.iloc[-1, 3:14].values.reshape(1, -1)  # Reshape for a single sample

Mean Squared Error: 0.0009191900794361619

In [35]:
# Standardize the features for 2025 using the same scaler
features_2025_scaled = scaler.transform(features_2025)

In [36]:
# Predict diabetes rates for 2025
predicted_diabetes_rate_2025 = model.predict(features_2025_scaled)[0]

Predictions exported to: output_directory_path\predictions_2024.xlsx

In [37]:
# Step 4: Append Predictions to the DataFrame
# Add a new row to the DataFrame for the year 2025 and fill in the predicted value
df_2025 = df_merged.iloc[-1].copy()  # Copy the last row
df_2025['Year'] = 2025
df_2025['Diabetes_Rate_2025'] = predicted_diabetes_rate_2025

In [38]:
# Append the new row to the original DataFrame
df_merged = df_merged.append(df_2025, ignore_index=True)

In [39]:
X_2025_encoded = pd.get_dummies(X_2025, drop_first=True)
X_2025_encoded = X_2025_encoded.reindex(columns=X_train.columns, fill_value=0)

In [40]:
y_pred_2025 = model.predict(X_2025_encoded)

In [41]:
copied_df_2025['2025_% Adults with Diabetes'] = y_pred_2025

In [42]:
output_filename_2025 = 'predictions_2025.xlsx'
output_file_2025 = os.path.join(output_directory, output_filename_2025)
copied_df_2025.to_excel(output_file_2025, index=False)
print(f"Predictions for 2025 exported to: {output_file_2025}")

Predictions for 2025 exported to: output_directory_path\predictions_2025.xlsx

In [43]:
copied_df_2025["2025_% Adults with Diabetes"] = copied_df_2025["2025_% Adults with Diabetes"].round(1)

In [44]:
output_directory = 'output_directory_path'
output_filename = 'copied_df_2025.xlsx'
output_file = os.path.join(output_directory, output_filename)

copied_df_2025.to_excel(output_file, index=False)
print(f"DataFrame exported to: {output_file}")

DataFrame exported to: output_directory_path\copied_df_2025.xlsx

In [45]:
copied_df_2025

,FIPS,State,County,2013_% Adults with Diabetes,2014_% Adults with Diabetes,2015_% Adults with Diabetes,2016_% Adults with Diabetes,2017_% Adults with Diabetes,2018_% Adults with Diabetes,2019_% Adults with Diabetes,2020_% Adults with Diabetes,2021_% Adults with Diabetes,2022_% Adults with Diabetes,2023_% Adults with Diabetes,2024_% Adults with Diabetes,2025_% Adults with Diabetes
0,1000,Alabama,0,12.7,0.0,0.0,0.0,0.0,0.0,0.0,14.2,14.5,12.2,13.0,11.1,11.1
1,1001,Alabama,Autauga,12.3,11.8,12.1,10.9,13.0,12.4,14.2,11.1,12.7,11.2,10.6,10.0,10.0
2,1003,Alabama,Baldwin,11.4,11.8,11.5,10.9,10.4,11.1,11.3,10.7,10.3,9.4,9.7,10.7,10.7
3,1005,Alabama,Barbour,14.0,14.2,14.8,15.3,18.4,18.2,18.0,17.6,17.5,16.5,15.6,12.8,12.8
4,1007,Alabama,Bibb,11.8,11.1,12.7,12.5,14.8,14.6,14.9,14.5,13.6,12.7,12.2,11.6,11.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Wyoming,Sweetwater,6.8,7.1,7.6,7.6,8.1,7.9,8.4,8.8,8.3,8.3,7.9,7.6,7.6
3189,56039,Wyoming,Teton,4.0,3.9,4.3,6.8,4.8,4.5,4.2,2.2,2.4,6.6,6.3,6.9,6.9
3190,56041,Wyoming,Uinta,7.0,7.4,8.2,8.3,9.0,10.0,9.3,11.3,10.3,8.3,7.8,8.9,8.9
3191,56043,Wyoming,Washakie,8.8,8.5,9.7,10.5,12.0,11.5,10.9,11.7,10.7,8.9,8.0,9.8,9.8
3192,56045,Wyoming,Weston,7.4,8.3,8.5,9.1,10.0,10.2,9.4,9.0,11.1,8.3,7.8,8.7,8.7